/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author andre
 */
public class FormularioCliente extends javax.swing.JFrame {

    /**
     * Creates new form ClientePanel
     */
    public FormularioCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        Parte_Alta = new javax.swing.JPanel();
        Cliente = new javax.swing.JLabel();
        Buscado = new java.awt.TextField();
        Usuario = new javax.swing.JPanel();
        idNumber = new java.awt.TextField();
        Nombre = new javax.swing.JLabel();
        NombreCliente = new java.awt.TextField();
        Apellido = new javax.swing.JLabel();
        ApellidoCliente = new java.awt.TextField();
        Direccion = new javax.swing.JLabel();
        DireccionCliente = new java.awt.TextField();
        TlfCliente = new java.awt.TextField();
        Email = new javax.swing.JLabel();
        EmailCliente = new java.awt.TextField();
        Tlf = new javax.swing.JLabel();
        Cliente_id = new javax.swing.JLabel();
        Botones = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        back = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();
        backStop = new javax.swing.JButton();
        playLeft = new javax.swing.JButton();
        playRight = new javax.swing.JButton();
        backStopRight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FormularioCliente");
        setBackground(new java.awt.Color(255, 255, 255));

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setPreferredSize(new java.awt.Dimension(591, 428));

        Parte_Alta.setBackground(new java.awt.Color(153, 153, 255));
        Parte_Alta.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        Cliente.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Cliente.setText("Clientes");
        Cliente.setToolTipText("");
        Parte_Alta.add(Cliente);

        Buscado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Buscado.setName(""); // NOI18N
        Buscado.setPreferredSize(new java.awt.Dimension(120, 20));
        Buscado.setText("textField1");
        Buscado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscadoActionPerformed(evt);
            }
        });
        Parte_Alta.add(Buscado);

        Usuario.setBackground(new java.awt.Color(255, 255, 255));

        idNumber.setBackground(new java.awt.Color(153, 153, 153));
        idNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        idNumber.setEditable(false);
        idNumber.setText("5");
        idNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNumberActionPerformed(evt);
            }
        });

        Nombre.setText("NOMBRE");

        NombreCliente.setText("RICARDO");
        NombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreClienteActionPerformed(evt);
            }
        });

        Apellido.setText("APELLIDOS");

        ApellidoCliente.setMinimumSize(new java.awt.Dimension(63, 20));
        ApellidoCliente.setText("MARTINES JUAREZ");
        ApellidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoClienteActionPerformed(evt);
            }
        });

        Direccion.setText("DIRECCION");

        DireccionCliente.setText("EJIDO MVO AMANECER");
        DireccionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionClienteActionPerformed(evt);
            }
        });

        TlfCliente.setText("RICA8586@GMAIL.COM");
        TlfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TlfClienteActionPerformed(evt);
            }
        });

        Email.setText("EMAIL");

        EmailCliente.setText("605096208");
        EmailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailClienteActionPerformed(evt);
            }
        });

        Tlf.setText("TELEFONO");

        Cliente_id.setText("CLIENTE_ID");

        javax.swing.GroupLayout UsuarioLayout = new javax.swing.GroupLayout(Usuario);
        Usuario.setLayout(UsuarioLayout);
        UsuarioLayout.setHorizontalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tlf, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cliente_id, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ApellidoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DireccionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(TlfCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmailCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UsuarioLayout.setVerticalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cliente_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tlf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TlfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Botones.setBackground(new java.awt.Color(255, 255, 255));
        Botones.setForeground(new java.awt.Color(255, 255, 255));
        Botones.setPreferredSize(new java.awt.Dimension(550, 101));
        Botones.setLayout(new java.awt.GridLayout(1, 8, 10, 20));

        add.setBackground(new java.awt.Color(204, 255, 255));
        add.setForeground(new java.awt.Color(102, 255, 255));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloveimg-resized (1)/add.png"))); // NOI18N
        Botones.add(add);

        back.setBackground(new java.awt.Color(204, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloveimg-resized (1)/left.png"))); // NOI18N
        Botones.add(back);

        delete.setBackground(new java.awt.Color(204, 255, 255));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloveimg-resized (1)/erase.png"))); // NOI18N
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        Botones.add(delete);

        save.setBackground(new java.awt.Color(204, 255, 255));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloveimg-resized (1)/save (1).png"))); // NOI18N
        Botones.add(save);

        backStop.setBackground(new java.awt.Color(204, 255, 255));
        backStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloveimg-resized (1)/arrow_stop_left.png"))); // NOI18N
        Botones.add(backStop);

        playLeft.setBackground(new java.awt.Color(204, 255, 255));
        playLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloveimg-resized (1)/controls_play_back_32.png"))); // NOI18N
        Botones.add(playLeft);

        playRight.setBackground(new java.awt.Color(204, 255, 255));
        playRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloveimg-resized (1)/play.png"))); // NOI18N
        playRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playRightActionPerformed(evt);
            }
        });
        Botones.add(playRight);

        backStopRight.setBackground(new java.awt.Color(204, 255, 255));
        backStopRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iloveimg-resized (1)/arrow_stop_right.png"))); // NOI18N
        Botones.add(backStopRight);

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Botones, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Parte_Alta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(Parte_Alta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Botones, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idNumberActionPerformed

    private void DireccionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionClienteActionPerformed

    private void TlfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TlfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TlfClienteActionPerformed

    private void ApellidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoClienteActionPerformed

    private void EmailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailClienteActionPerformed

    private void NombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreClienteActionPerformed

    private void BuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscadoActionPerformed

    private void playRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playRightActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private java.awt.TextField ApellidoCliente;
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel Botones;
    private java.awt.TextField Buscado;
    private javax.swing.JLabel Cliente;
    private javax.swing.JLabel Cliente_id;
    private javax.swing.JLabel Direccion;
    private java.awt.TextField DireccionCliente;
    private javax.swing.JLabel Email;
    private java.awt.TextField EmailCliente;
    private javax.swing.JLabel Nombre;
    private java.awt.TextField NombreCliente;
    private javax.swing.JPanel Parte_Alta;
    private javax.swing.JLabel Tlf;
    private java.awt.TextField TlfCliente;
    private javax.swing.JPanel Usuario;
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton backStop;
    private javax.swing.JButton backStopRight;
    private javax.swing.JButton delete;
    private java.awt.TextField idNumber;
    private javax.swing.JButton playLeft;
    private javax.swing.JButton playRight;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
